Reduce to single test for testing.

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -98,7 +98,7 @@ jobs:
     name: Run tests
     runs-on: [self-hosted, gpu]
     timeout-minutes: 80
-    needs: [pre_commit]
+    # needs: [pre_commit]
 
     container:
       image: nvcr.io/nvstaging/isaac-amr/isaaclab_arena:latest
@@ -144,130 +144,134 @@ jobs:
       # - All subprocess-spawning tests (each spawns their own SimulationApp)
       #
       # To restore sanity here is a goal for Isaac Lab Arena v0.3.
-      - name: Run in-process Newton tests
-        run: |
-          /isaac-sim/python.sh -m pytest -sv --durations=0 -m with_newton \
-            isaaclab_arena/tests/
+      # - name: Run in-process Newton tests
+      #   run: |
+      #     /isaac-sim/python.sh -m pytest -sv --durations=0 -m with_newton \
+      #       isaaclab_arena/tests/
 
-      - name: Run in-process PhysX tests without cameras
-        run: |
-          /isaac-sim/python.sh -m pytest -sv --durations=0 -m "not with_cameras and not with_subprocess and not with_newton" \
-            isaaclab_arena/tests/
+      # - name: Run in-process PhysX tests without cameras
+      #   run: |
+      #     /isaac-sim/python.sh -m pytest -sv --durations=0 -m "not with_cameras and not with_subprocess and not with_newton" \
+      #       isaaclab_arena/tests/
 
-      - name: Run in-process PhysX tests with cameras
-        run: |
-          /isaac-sim/python.sh -m pytest -sv --durations=0 -m "with_cameras and not with_subprocess and not with_newton" \
-            isaaclab_arena/tests/
+      # - name: Run in-process PhysX tests with cameras
+      #   run: |
+      #     /isaac-sim/python.sh -m pytest -sv --durations=0 -m "with_cameras and not with_subprocess and not with_newton" \
+      #       isaaclab_arena/tests/
 
-      - name: Run subprocess-spawning PhysX tests
-        run: |
-          ISAACLAB_ARENA_SUBPROCESS_TIMEOUT=900 \
-          /isaac-sim/python.sh -m pytest -sv --durations=0 -m with_subprocess \
-            isaaclab_arena/tests/
+      # - name: Run subprocess-spawning PhysX tests
+      #   run: |
+      #     ISAACLAB_ARENA_SUBPROCESS_TIMEOUT=900 \
+      #     /isaac-sim/python.sh -m pytest -sv --durations=0 -m with_subprocess \
+      #       isaaclab_arena/tests/
 
-
-  test_policy:
-    name: Run policy-related tests with GR00T & cuda12_8 deps
-    runs-on: [self-hosted, gpu]
-    timeout-minutes: 60
-    needs: [pre_commit]
-
-    container:
-      image: nvcr.io/nvstaging/isaac-amr/isaaclab_arena:cuda_gr00t_gn16
-      credentials:
-        username: $oauthtoken
-        password: ${{ env.NGC_API_KEY }}
-    env:
-      GROOT_DEPS_DIR: /opt/groot_deps
-    steps:
-      # nvidia-smi
-      - *nvidia_smi
-      - *lscpu
-
-      # Setup.
-      - *install_git_step
-      - *cleanup_step
-      - *mark_repo_safe_step
-      - *checkout_step
-      - *git_lfs_step
-      - *install_project_step
-
-      # Run the policy (GR00T) related tests.
-      - name: Run policy-related pytest
+      - name: Run a single camera-requiring test
         run: |
           ISAACLAB_ARENA_SUBPROCESS_TIMEOUT=900 \
-          /isaac-sim/python.sh -m pytest -sv --durations=0 isaaclab_arena_gr00t/tests/
+          /isaac-sim/python.sh -m pytest -sv --durations=0 isaaclab_arena/tests/test_camera_observation.py
+
+  # test_policy:
+  #   name: Run policy-related tests with GR00T & cuda12_8 deps
+  #   runs-on: [self-hosted, gpu]
+  #   timeout-minutes: 60
+  #   needs: [pre_commit]
+
+  #   container:
+  #     image: nvcr.io/nvstaging/isaac-amr/isaaclab_arena:cuda_gr00t_gn16
+  #     credentials:
+  #       username: $oauthtoken
+  #       password: ${{ env.NGC_API_KEY }}
+  #   env:
+  #     GROOT_DEPS_DIR: /opt/groot_deps
+  #   steps:
+  #     # nvidia-smi
+  #     - *nvidia_smi
+  #     - *lscpu
+
+  #     # Setup.
+  #     - *install_git_step
+  #     - *cleanup_step
+  #     - *mark_repo_safe_step
+  #     - *checkout_step
+  #     - *git_lfs_step
+  #     - *install_project_step
+
+  #     # Run the policy (GR00T) related tests.
+  #     - name: Run policy-related pytest
+  #       run: |
+  #         ISAACLAB_ARENA_SUBPROCESS_TIMEOUT=900 \
+  #         /isaac-sim/python.sh -m pytest -sv --durations=0 isaaclab_arena_gr00t/tests/
 
 
-  build_docs_pre_merge:
-    name: Build the docs (pre-merge)
-    runs-on: [self-hosted, gpu]
-    timeout-minutes: 30
-    needs: [pre_commit]
+  # build_docs_pre_merge:
+  #   name: Build the docs (pre-merge)
+  #   runs-on: [self-hosted, gpu]
+  #   timeout-minutes: 30
+  #   needs: [pre_commit]
 
-    container:
-      image: python:3.11-slim
+  #   container:
+  #     image: python:3.11-slim
 
-    steps:
-      # Setup.
-      - *install_git_step
-      - *mark_repo_safe_step
-      - *cleanup_step
+  #   steps:
+  #     # Setup.
+  #     - *install_git_step
+  #     - *mark_repo_safe_step
+  #     - *cleanup_step
 
-      - name: Checkout Code
-        uses: actions/checkout@v4
+  #     - name: Checkout Code
+  #       uses: actions/checkout@v4
 
-      # Build docs for the current branch (validates PR changes)
-      - name: Build docs
-        working-directory: ./docs
-        run: |
-          pip3 install -r requirements.txt
-          make SPHINXOPTS=-W html
+  #     # Build docs for the current branch (validates PR changes)
+  #     - name: Build docs
+  #       working-directory: ./docs
+  #       run: |
+  #         pip3 install -r requirements.txt
+  #         make SPHINXOPTS=-W html
 
 
-  build_and_push_image_post_merge:
-    name: Build & push NGC image (post-merge)
-    runs-on: [self-hosted, gpu]
-    timeout-minutes: 90
-    needs: [test, test_policy]       # only push if tests passed
-    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
+  # build_and_push_image_post_merge:
+  #   name: Build & push NGC image (post-merge)
+  #   runs-on: [self-hosted, gpu]
+  #   timeout-minutes: 90
+  #   needs: [test, test_policy]       # only push if tests passed
+  #   if: github.event_name == 'push' && github.ref == 'refs/heads/main'
 
-    container:
-      image: ubuntu:latest
+  #   container:
+  #     image: ubuntu:latest
 
-    env:
-      # already defined at top, but keep here for clarity/local override if needed
-      NGC_API_KEY: ${{ secrets.ARENA_NGC_API_KEY }}
+  #   env:
+  #     # already defined at top, but keep here for clarity/local override if needed
+  #     NGC_API_KEY: ${{ secrets.ARENA_NGC_API_KEY }}
 
-    steps:
-      # Setup.
-      - *install_git_step
-      - *mark_repo_safe_step
-      - *cleanup_step
-      - *checkout_step
+  #   steps:
+  #     # Setup.
+  #     - *install_git_step
+  #     - *mark_repo_safe_step
+  #     - *cleanup_step
+  #     - *checkout_step
 
-      - name: Install docker
-        run: |
-          apt-get update
-          apt-get install -y ca-certificates curl gnupg && \
-          install -m 0755 -d /etc/apt/keyrings && \
-          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg && \
-          chmod a+r /etc/apt/keyrings/docker.gpg && \
-          echo "deb [arch="$(dpkg --print-architecture)" signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
-          "$(. /etc/os-release && echo "$VERSION_CODENAME")" stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null &&
-          apt-get update && apt-get install -y docker.io docker-buildx-plugin
-          docker --version
+  #     - name: Install docker
+  #       run: |
+  #         apt-get update
+  #         apt-get install -y ca-certificates curl gnupg && \
+  #         install -m 0755 -d /etc/apt/keyrings && \
+  #         curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg && \
+  #         chmod a+r /etc/apt/keyrings/docker.gpg && \
+  #         echo "deb [arch="$(dpkg --print-architecture)" signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
+  #         "$(. /etc/os-release && echo "$VERSION_CODENAME")" stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null &&
+  #         apt-get update && apt-get install -y docker.io docker-buildx-plugin
+  #         docker --version
 
-      - name: Docker login to NGC
-        # $oauthtoken is the literal NGC username; pipe the NGC API key via stdin
-        run: echo "${NGC_API_KEY}" | docker login nvcr.io -u '$oauthtoken' --password-stdin
+  #     - name: Docker login to NGC
+  #       # $oauthtoken is the literal NGC username; pipe the NGC API key via stdin
+  #       run: echo "${NGC_API_KEY}" | docker login nvcr.io -u '$oauthtoken' --password-stdin
 
-      - name: Build & push image to NGC
-        run: |
-          chmod +x ./docker/push_to_ngc* || true
-          ./docker/push_to_ngc.sh -p
+  #     - name: Build & push image to NGC
+  #       run: |
+  #         chmod +x ./docker/push_to_ngc* || true
+  #         ./docker/push_to_ngc.sh -p
 
-      - name: Build & push image to NGC (GR00T Image)
-        run: |
-          chmod +x ./docker/push_to_ngc* || true
-          ./docker/push_to_ngc.sh -p -g -t cuda_gr00t_gn16
+  #     - name: Build & push image to NGC (GR00T Image)
+  #       run: |
+  #         chmod +x ./docker/push_to_ngc* || true
+  #         ./docker/push_to_ngc.sh -p -g -t cuda_gr00t_gn16
